### ISSUE TITLE
Failed resolution of: Lcom/apollographql/apollo3/api/EnumType

### ISSUE THREAD

**Issue by DuduFiverrCohen** [apollographql/apollo-kotlin#4274]
### Question
After migration to v3 all schema enums are set with EnumType class. that class field to compile at the client side and we get an Exception: 
> Fatal Exception: java.lang.NoClassDefFoundError
Failed resolution of: Lcom/apollographql/apollo3/api/EnumType; 

The generate Enum class is: 

```
public enum class Interval(
  public val rawValue: String,
) {
  MONTH("MONTH"),
  WEEK("WEEK"),
  /**
   * Auto generated constant for unknown enum values
   */
  UNKNOWN__("UNKNOWN__"),
  ;

  public companion object {
    public val type: EnumType = EnumType("Interval")

    public fun safeValueOf(rawValue: String): Interval = values().find { it.rawValue == rawValue }
        ?: UNKNOWN__

    /**
     * Returns all [Interval] known at compile time
     */
    public fun knownValues(): Array<Interval> = arrayOf(
      MONTH,
      WEEK)
  }
}
``` 

Any idea how to solve this? 

Thanks.

**Comment by martinbonnin** [comment]
Hi 👋 

Can you make sure you added `com.apollographql.apollo3:apollo-runtime` to your dependencies? Looks like you still have the older one or something like this.

**Comment by DuduFiverrCohen** [comment]
Hi, yes.

My dependencies:

`      dependencies {
                implementation("com.apollographql.apollo3:apollo-runtime:3.4.0")
                implementation("com.apollographql.apollo3:apollo-api:3.4.0")

                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.1")
            }`

**Comment by martinbonnin** [comment]
That looks about right 👍 Do you mind sharing the full stacktrace from Gradle? From the command line, you can have it with something like this:

```
./gradlew generateApolloSources --stacktrace
```

**Comment by DuduFiverrCohen** [comment]
Found the problem... in a weird way our client have a dependency to `apollo-runtime` too and it was set to an old version.
After I removed that dependency all worked.

Thank you @martinbonnin.

I'm closing this ticket.
